### ISSUE TITLE
[Feature advice]Responsive width of applet

### ISSUE THREAD

**Issue by svenhsia** [IKRadulov/mate-window-applets#7] opened 2017-09-07 13:00 UTC
Firstly, thanks for this excellent applet which works smoothly.

I highly recommend you make the width of applet in panel responsive according to different conditions. For example, when windows lose focus, the width of applet shrinks to 0. This will avoid the blank place token by the applet when no windows is on focus. Even if possible, the buttons appear only if the windows is maximized.

**Comment by IKRadulov** [comment] 2017-09-07 22:50
The applet is event responsive . That is why it shrinks to 0 when no window is focused or when window does not have a certain action it shrinks size . The problem is that mate-panel uses fixed position for applets unlike the xfce panel which loads them in a container that resizes its shildren . I use a hack method for removing the empty space that is left by the buttons . 
Here is the way of removing it : 
1. Add buttons applet to panel .
2. Lock the buttons applet via right click -> lock to panel
3. Add global menu bar (or any other applet) to the right side (or the left depending on your desires).
4. Focus the desktop so that applet size is 0 (No buttons shown).
5. Move the global menu bar (or any other applet) to the buttons applet untill it can't be moved anymore ('couse buttons applet is locked and it doesn't allow other applets to past after it).
6. Lock the other applet .
This works 'couse windows buttons pushes the other applet .
The only thing I can do else is make them inactive when no "window" is focused . And it has to be a options since some people may not like this .

As for the maximized window control . I will do it in next (non-bugfix) release .

**Comment by svenhsia** [comment] 2017-09-08 22:08
That works ! Thanks a lot.
By the way, I find that the buttons show on the panel when the desktop is loaded. I need to open and close an app to turn that off. I think this may be a bug.

**Comment by IKRadulov** [comment] 2017-09-08 22:51
I replacated this . Didn't notice before . Fixing it tommorow .

**Comment by IKRadulov** [comment] 2017-09-09 16:48
It should be fixed in master now.

**Comment by IKRadulov** [comment] 2017-09-10 13:35
Controlling only maximized window is done and arrives soon at master as of version 1.5.

**Closed by IKRadulov** 2017-09-10 13:35 UTC
Labels: bug, enhancement
